# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title:
  fr: ADDED
  en: ADDED
description:
  fr: |
    L'Association des Doctorants et Docteurs
    des Écoles Doctorales PSIME & MIIS
    sur Rouen & Le Havre
  en: |
    The Association of PhD students and Doctors
    of the Doctoral Schools PSIME & MIIS
    at Rouen & le Havre
index:
  fr:
  en: index-en
feed:
  fr: /feed.xml
  en: /feed-en.xml
owner:
  name: ADDED # or company name
  email: association.added@gmail.com
  url: https://asso-added.github.io
first_published: 2017 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asso-added.github.io" # the base hostname & protocol for your site
banner: "/images/rouen.jpg"
knowmore:
  fr: En savoir plus
  en: know more about
fillupform:
  fr: Remplir le formulaire
  en: Fill in the form
downloadlist:
  fr: Télécharger la liste (*.pdf)
  en: Download the list (*.pdf)

lang: fr  # the default langauge. (_layout/default.html)
navig-posts-lang:
  next:
    en: Next >
    fr: Suivant >
  back:
    en: < Back
    fr: < Précédent
lang-text:
  fr: Français
  en: English
date-trans:
  January:
    en: January
    fr: Janvier
  February:
    en: February
    fr: Février
  March:
    en: March
    fr: Mars
  April:
    en: April
    fr: Avril
  May:
    en: May
    fr: Mai
  June:
    en: June
    fr: Juin
  July:
    en: July
    fr: Juillet
  August:
    en: August
    fr: Août
  September:
    en: September
    fr: Septembre
  October:
    en: October
    fr: Octobre
  November:
    en: November
    fr: Novembre
  December:
    en: December
    fr: Décembre

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title:
    fr: À propos
    en: About
  text:
# - title for your blog's featured posts
features-title: Featured topics
# - displayed at the bottom
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!

# on all pages (and the first three you list display with greeting, if included)
social:
  email: association.added@gmail.com
  #twitter: https://twitter.com/arkadianriver
  github: https://github.com/asso-added
  #linkedin-square: https://linkedin.com/in/garyfaircloth
  #facebook-official: https://facebook.com/gary.faircloth
  #google-plus-square: https://plus.google.com/u/0/+GaryFaircloth
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages', '.htaccess']
future: true  # display future posts (as upcoming news)
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
